name: smart_meal_ta
description: "Tugas Akhir - Smart Meal Planner and Budgeting App menggunakan Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  google_maps_flutter: ^2.5.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  # --- State Management ---
  # Digunakan di folder /providers
  provider: ^6.1.2

  # --- Database & Storage ---
  # Digunakan di /services/database_service.dart
  sqflite: ^2.3.0
  path: ^1.8.3
  # Untuk menangani Session & Token secara aman
  flutter_secure_storage: ^9.0.0

  # --- Networking & AI ---
  # Digunakan di /services/api_service.dart dan /services/ai_service.dart
  http: ^0.13.3
  dio: ^5.4.1
  # yey# Library LLM Gemini

  # --- Security & Auth ---
  # Digunakan di /services/auth_service.dart dan /services/encryption_service.dart
  local_auth: ^2.1.6 # Login Biometric
  shared_preferences: ^2.2.0
  crypto: ^3.0.3     # Enkripsi manual (SHA-256)

  # --- Location Based Services (LBS) ---
  # Digunakan di /services/location_service.dart
  geolocator: ^11.0.0
  # google_maps_flutter: ^2.5.3

  # flutter_local_notifications: ^17.0.0

  # --- Sensors ---
  # Digunakan di /services/sensor_service.dart (Shake/Accelerometer)
  sensors_plus: ^4.0.2

  # --- Utilities & Configuration ---
  # Untuk membaca file .env
  flutter_dotenv: ^5.1.0
  # Format mata uang & waktu (WIB, London, dll)
  intl: ^0.19.0
  timezone: ^0.9.4
  # Untuk ambil foto profil di /screens/profile_page.dart
  image_picker: ^1.0.7

  # --- Game Engine ---
  # Digunakan di folder /game
  flame: ^1.14.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Pendaftaran Assets
  assets:
    - .env
    - assets/images/smartbite_logo.png
  #  - assets/images/
  #  - assets/icons/
    # - assets/audio/ # Jika game butuh suara

  # Catatan: Jika ingin menggunakan font khusus agar mirip desain UI
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
